version: '3'

services:
    web:
        build:
        context: .
        dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        depends_on:
            - php
    php:
        build:
        context: .
        dockerfile: Dockerfile.php
        volumes:
            - .:/var/www
    db:
        image: mysql
        ports:
            - "8001:5432"
